apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080 # Service port
    targetPort: 8080 # Pod port
  type: ClusterIP # Internal service